### ISSUE TITLE
Global Search

### ISSUE THREAD

**Issue by zven21** [zven21/mipha#15]
## Tasks

- [ ] Support search users
- [ ] Support search reply
- [ ] Support search topic

## References

- https://ruby-china.org/search?q=elixir
