### ISSUE TITLE
Job processing 

### ISSUE THREAD

**Issue by zven21** [zven21/mipha#22]
## Tasks

- [ ] Notification queue push.
- [ ] Sent email queue.
- [ ] Fetch user && team `github repos` queue.

## References

- [https://github.com/akira/exq](https://github.com/akira/exq)
